name: Bash Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "*" ]

jobs:
  lint:
    name: Lint Bash Scripts
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Run shellcheck
        run: shellcheck LFC/LFC.sh
